// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { getAppConfig, useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { onMount, beforeUpdate, afterUpdate, onDestroy, tick, setContext, getContext, hasContext, getAllContexts, createEventDispatcher } from 'svelte';
  export { fakeBrowser } from 'wxt/testing/fake-browser';
  export { clearCache, buildCachePrefix, countCached, withCache } from '../utils/cache';
  export { LANGUAGES, languageName, isoFromCode } from '../utils/languages';
  export { profileFor, listLmModels, isLoaded, loadLmModel, cachedProfile, ensureLmModelLoaded, forgetEnsured, LmModel, ModelProfile } from '../utils/lmstudio';
  export { cancelActive, translateBatch, parseTranslations } from '../utils/providers';
  export { DEFAULT_SETTINGS, loadSettings, saveSettings, ProviderId, Settings } from '../utils/settings';
}
