// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const DEFAULT_SETTINGS: typeof import('C:/Users/William/Documents/Development/rosetta/utils/settings').DEFAULT_SETTINGS
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const LANGUAGES: typeof import('C:/Users/William/Documents/Development/rosetta/utils/languages').LANGUAGES
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const afterUpdate: typeof import('svelte').afterUpdate
  const beforeUpdate: typeof import('svelte').beforeUpdate
  const browser: typeof import('wxt/browser').browser
  const buildCachePrefix: typeof import('C:/Users/William/Documents/Development/rosetta/utils/cache').buildCachePrefix
  const cachedProfile: typeof import('C:/Users/William/Documents/Development/rosetta/utils/lmstudio').cachedProfile
  const cancelActive: typeof import('C:/Users/William/Documents/Development/rosetta/utils/providers').cancelActive
  const clearCache: typeof import('C:/Users/William/Documents/Development/rosetta/utils/cache').clearCache
  const countCached: typeof import('C:/Users/William/Documents/Development/rosetta/utils/cache').countCached
  const createEventDispatcher: typeof import('svelte').createEventDispatcher
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const ensureLmModelLoaded: typeof import('C:/Users/William/Documents/Development/rosetta/utils/lmstudio').ensureLmModelLoaded
  const fakeBrowser: typeof import('wxt/testing/fake-browser').fakeBrowser
  const forgetEnsured: typeof import('C:/Users/William/Documents/Development/rosetta/utils/lmstudio').forgetEnsured
  const getAllContexts: typeof import('svelte').getAllContexts
  const getAppConfig: typeof import('wxt/utils/app-config').getAppConfig
  const getContext: typeof import('svelte').getContext
  const hasContext: typeof import('svelte').hasContext
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const isLoaded: typeof import('C:/Users/William/Documents/Development/rosetta/utils/lmstudio').isLoaded
  const isoFromCode: typeof import('C:/Users/William/Documents/Development/rosetta/utils/languages').isoFromCode
  const languageName: typeof import('C:/Users/William/Documents/Development/rosetta/utils/languages').languageName
  const listLmModels: typeof import('C:/Users/William/Documents/Development/rosetta/utils/lmstudio').listLmModels
  const loadLmModel: typeof import('C:/Users/William/Documents/Development/rosetta/utils/lmstudio').loadLmModel
  const loadSettings: typeof import('C:/Users/William/Documents/Development/rosetta/utils/settings').loadSettings
  const onDestroy: typeof import('svelte').onDestroy
  const onMount: typeof import('svelte').onMount
  const parseTranslations: typeof import('C:/Users/William/Documents/Development/rosetta/utils/providers').parseTranslations
  const profileFor: typeof import('C:/Users/William/Documents/Development/rosetta/utils/lmstudio').profileFor
  const saveSettings: typeof import('C:/Users/William/Documents/Development/rosetta/utils/settings').saveSettings
  const setContext: typeof import('svelte').setContext
  const storage: typeof import('wxt/utils/storage').storage
  const tick: typeof import('svelte').tick
  const translateBatch: typeof import('C:/Users/William/Documents/Development/rosetta/utils/providers').translateBatch
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const withCache: typeof import('C:/Users/William/Documents/Development/rosetta/utils/cache').withCache
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { WxtStorage, WxtStorageItem, StorageArea, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { LmModel, ModelProfile } from 'C:/Users/William/Documents/Development/rosetta/utils/lmstudio'
  import('C:/Users/William/Documents/Development/rosetta/utils/lmstudio')
  // @ts-ignore
  export type { ProviderId, Settings } from 'C:/Users/William/Documents/Development/rosetta/utils/settings'
  import('C:/Users/William/Documents/Development/rosetta/utils/settings')
}
